##
## Makefile for  in /home/munoz_d/cpp_arcade/games
## 
## Made by David Munoz
## Login   <david.munoz@epitech.eu>
## 
## Started on  Sun Apr  9 20:40:29 2017 David Munoz
## Last update Sun Apr  9 21:01:51 2017 David Munoz
##

all	:
	(cd ncurses; make all)
	(cd openGl; make all)
	(cd sdl; make all)

re	:
	(cd ncurses; make re)
	(cd openGl; make re)
	(cd sdl; make re)

clean	:
	(cd ncurses; make clean)
	(cd openGl; make clean)
	(cd sdl; make clean)

fclean	:
	(cd ncurses; make fclean)
	(cd openGl; make fclean)
	(cd sdl; make fclean)

.PHONY: all clean fclean re
