##
## Makefile for  in /home/munoz_d/cpp_arcade/games
## 
## Made by David Munoz
## Login   <david.munoz@epitech.eu>
## 
## Started on  Sun Apr  9 20:40:29 2017 David Munoz
## Last update Sun Apr  9 23:15:01 2017 Adrien Missioux
##

all	:
	(cd pacman; make all)
	(cd snake; make all)

re	:
	(cd pacman; make re)
	(cd snake; make re)

clean	:
	(cd pacman; make clean)
	(cd snake; make clean)

fclean	:
	(cd pacman; make fclean)
	(cd snake; make fclean)

.PHONY: all clean fclean re
